### PR TITLE
Add README link

### PR DESCRIPTION
**Pull request by dpear**
Nothing major changed except the README to include a link to the biorXiv fish microbiome paper.

### CODE REVIEW

**Comment by antgonza** [comment]
@dpear, can you pull from upstream and update this PR?

**Comment by dpear** [comment]
Incorporated changes from code review:
- added helper function for fitting lm in estimating biomass and biomass plot
- fixed typo in atcc dictionary

**Comment by dpear** [comment]
Add the DOI to the github page @antgonza

**Comment by antgonza** [comment]
Looks good but there seems to be a lot of "old" commits here, no? @dpear, could you update it so only the newest ones are shown? Thank you.

**Pull request merged**
